// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package mypersonpkg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyPersonRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyPersonRequest) Reset()         { *m = MyPersonRequest{} }
func (m *MyPersonRequest) String() string { return proto.CompactTextString(m) }
func (*MyPersonRequest) ProtoMessage()    {}
func (*MyPersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *MyPersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyPersonRequest.Unmarshal(m, b)
}
func (m *MyPersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyPersonRequest.Marshal(b, m, deterministic)
}
func (m *MyPersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyPersonRequest.Merge(m, src)
}
func (m *MyPersonRequest) XXX_Size() int {
	return xxx_messageInfo_MyPersonRequest.Size(m)
}
func (m *MyPersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MyPersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MyPersonRequest proto.InternalMessageInfo

func (m *MyPersonRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MyPersonResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyPersonResponse) Reset()         { *m = MyPersonResponse{} }
func (m *MyPersonResponse) String() string { return proto.CompactTextString(m) }
func (*MyPersonResponse) ProtoMessage()    {}
func (*MyPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *MyPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyPersonResponse.Unmarshal(m, b)
}
func (m *MyPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyPersonResponse.Marshal(b, m, deterministic)
}
func (m *MyPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyPersonResponse.Merge(m, src)
}
func (m *MyPersonResponse) XXX_Size() int {
	return xxx_messageInfo_MyPersonResponse.Size(m)
}
func (m *MyPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MyPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MyPersonResponse proto.InternalMessageInfo

func (m *MyPersonResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MyPersonResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyPersonResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*MyPersonRequest)(nil), "mypersonpkg.MyPersonRequest")
	proto.RegisterType((*MyPersonResponse)(nil), "mypersonpkg.MyPersonResponse")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xce, 0xad, 0x84, 0xf0, 0x0b, 0xb2,
	0xd3, 0x95, 0x14, 0xb9, 0xf8, 0x7d, 0x2b, 0x03, 0xc0, 0xdc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2,
	0x12, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc,
	0x14, 0x25, 0x0f, 0x2e, 0x01, 0x84, 0x92, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x74, 0x35, 0x42,
	0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6,
	0x90, 0x00, 0x17, 0x73, 0x62, 0x7a, 0xaa, 0x04, 0x33, 0x58, 0x11, 0x88, 0x69, 0x14, 0x8b, 0xb0,
	0x2c, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x8b, 0x8b, 0xd3, 0x3d, 0xb5, 0x04, 0x22,
	0x26, 0x24, 0xa3, 0x87, 0xe4, 0x34, 0x3d, 0x34, 0x77, 0x49, 0xc9, 0xe2, 0x90, 0x85, 0x38, 0x49,
	0x89, 0x21, 0x89, 0x0d, 0xec, 0x3f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0xaa, 0x42,
	0x19, 0xef, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyPersonServiceClient is the client API for MyPersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyPersonServiceClient interface {
	GetPerson(ctx context.Context, in *MyPersonRequest, opts ...grpc.CallOption) (*MyPersonResponse, error)
}

type myPersonServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyPersonServiceClient(cc *grpc.ClientConn) MyPersonServiceClient {
	return &myPersonServiceClient{cc}
}

func (c *myPersonServiceClient) GetPerson(ctx context.Context, in *MyPersonRequest, opts ...grpc.CallOption) (*MyPersonResponse, error) {
	out := new(MyPersonResponse)
	err := c.cc.Invoke(ctx, "/mypersonpkg.MyPersonService/GetPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyPersonServiceServer is the server API for MyPersonService service.
type MyPersonServiceServer interface {
	GetPerson(context.Context, *MyPersonRequest) (*MyPersonResponse, error)
}

// UnimplementedMyPersonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMyPersonServiceServer struct {
}

func (*UnimplementedMyPersonServiceServer) GetPerson(ctx context.Context, req *MyPersonRequest) (*MyPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}

func RegisterMyPersonServiceServer(s *grpc.Server, srv MyPersonServiceServer) {
	s.RegisterService(&_MyPersonService_serviceDesc, srv)
}

func _MyPersonService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyPersonServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mypersonpkg.MyPersonService/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyPersonServiceServer).GetPerson(ctx, req.(*MyPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyPersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mypersonpkg.MyPersonService",
	HandlerType: (*MyPersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _MyPersonService_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
